<style>
    /* these styles are for the demo, but are not required for the plugin */
    .zoom {
        display: inline-block;
        position: relative;
    }

    /* magnifying glass icon */
    .zoom:after {
        content: '';
        display: block;
        width: 33px;
        height: 33px;
        position: absolute;
        top: 0;
        right: 0;
    }

    .zoom img {
        display: block;
    }
</style>
<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Chi tiết sản phẩm</h3></div>
        <div class="panel-body">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

                <img data-toggle="modal" data-target="#myModal" id="img-zoom"  width="100%" style="cursor: pointer" class="img-thumbnail"
                     src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/products/' . $product['product_picture'];?>&w=270&h=270&zc=0"
                      data-zoom-image="<?php echo $this->basePath() . '/public/pictures/products/' . $product['product_picture'];?>"
                     alt="post image">

                <img id="img_detail_mobile" data-toggle="modal" data-target="#myModal"  width="100%" style="cursor: pointer;" class="img-thumbnail"
                     src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/products/' . $product['product_picture'];?>&w=270&h=270&zc=0" alt="post image">

                <div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <img style="width: 100%" src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/products/' . $product['product_picture'];?>&w=500&zc=0" />
                        </div>
                    </div>
                </div>

                <div class="col-md-12" style="margin-top: 5px">
                    <table cellspacing="4" cellpadding="4" width="100%">
                        <tr>
                            <?php for($i=1; $i<=3; $i++) {?>
                            <td style="padding: 5px">
                                <?php
                                if ($product['product_picture_' . $i] != '') {?>
                                    <img data-toggle="modal" data-target="#myModal_<?php echo $i;?>" width="100%" style="cursor: pointer; width: 60px; height: 60px" class="img-thumbnail"
                                         src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/products/' . $product['product_picture_' . $i];?>&w=60&h=60&zc=0" alt="post image">
                                <?php }?>

                                <div id="myModal_<?php echo $i;?>" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <img style="width: 100%" src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/products/' . $product['product_picture_' . $i];?>&w=500&zc=0" />
                                        </div>
                                    </div>
                                </div>

                            </td>
                            <?php }?>
                        </tr>
                    </table>
                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8" style="padding-left: 15px;">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h4 style="margin-top: 5px; margin-bottom: 0; color: #0067bf; font-weight: bold"><?php echo $this->escapeHtml($product['product_name']);?></h4>
                        <br>
<!--                        <p>Mã sản phẩm: --><?php //echo $this->escapeHtml($product['product_code']);?><!--</p>-->
                        <?php echo $product['product_description'];?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-md-12">
    <div class="panel panel-primary group-item">
        <div class="panel-heading"><h3 class="panel-title">Sản phẩm cùng loại</h3></div>
        <div class="panel-body">
            <?php echo $this->partial('home/partial/product-item', array('products' => $productsOther)); ?>
        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        $("#img-zoom").elevateZoom();
    });
</script>